--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-tooling-eks
  region: eu-west-2
  version: '1.17'  

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  nat:
    gateway: HighlyAvailable
  id: "vpc-02b7a77c59dfe02ee"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.170.96.0/24"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      eu-west-2a:
        id: "infra-subprv-2a-devops"
        cidr: "10.170.96.0/25" # (optional, must match CIDR used by the given subnet)

      eu-west-2b:
        id: "infra-subprv-2b-devops"
        cidr: "10.170.96.128/25"  # (optional, must match CIDR used by the given subnet)
        

nodeGroups:
  - name: devops-tooling-node-group
    instanceType: m5.xlarge
    desiredCapacity: 4
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true    
    # privateNetworking must be explicitly set for a fully-private cluster
    # Rather than defaulting this field to true for a fully-private cluster, we require users to explicitly set it
    # to make the behaviour explicit and avoid confusion.
    privateNetworking: true

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

git:
  repo:
    url: "git@github.com:pol-onesource/devops-fluxcd-infra-tooling"
    branch: master
    fluxPath: "flux/"
    user: "aws-dev-ops-github-service"
    email: "aws-dev-ops-github-service@users.noreply.github.com"
  operator:
    namespace: "flux"
    withHelm: true
