--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-tooling-eks
  region: eu-west-2
  version: '1.17'  


vpc:
  nat:
    gateway: HighlyAvailable
  id: "vpc-02b7a77c59dfe02ee"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.170.96.0/24"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      eu-west-2a:
        id: "subnet-0332abfbaacc3e663"
        cidr: "10.170.96.0/25" # (optional, must match CIDR used by the given subnet)

      eu-west-2b:
        id: "subnet-0b066fecc17f18128"
        cidr: "10.170.96.128/25"  # (optional, must match CIDR used by the given subnet)
        

nodeGroups:
  - name: devops-tooling-ng-on-demand-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true  
    privateNetworking: true
    labels:
      instance-type: on-demand
    availabilityZones: ["eu-west-2a", "eu-west-2b"]  
  - name: devops-tooling-ng-on-demand-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true  
    privateNetworking: true
    labels:
      instance-type: on-demand
    availabilityZones: ["eu-west-2a", "eu-west-2b"]  


  # - name: devops-tooling-ng-spot-1
  #   desiredCapacity: 1
  #   minSize: 1
  #   maxSize: 10
  #   volumeType: gp2
  #   volumeSize: 100
  #   volumeEncrypted: true 
  #   privateNetworking: true
  #   instancesDistribution:
  #     instanceTypes: ["m5.large", "m4.large", "t3.large", "m5d.large", "m5ad.large","t3a.large"]
  #     onDemandBaseCapacity: 1
  #     onDemandPercentageAboveBaseCapacity: 1
  #     spotInstancePools: 6
  #   tags:
  #     k8s.io/cluster-autoscaler/node-template/label/instance-type: spot
  #   availabilityZones: ["eu-west-2a", "eu-west-2b"]
  #   labels:
  #     instance-type: spot
  #   iam:
  #     withAddonPolicies:
  #       autoScaler: true  

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

git:
  repo:
    url: "git@github.com:pol-onesource/devops-fluxcd-infra-tooling"
    branch: master
    fluxPath: "flux/"
    user: "aws-dev-ops-github-service"
    email: "aws-dev-ops-github-service@users.noreply.github.com"
  operator:
    namespace: "flux"
    withHelm: true
