--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shared-eks
  region: eu-west-1
  version: '1.17'  

vpc:
  id: "vpc-0b6187a14f11b4e69"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.20.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      eu-west-1a:
        id: "subnet-0b1e0849a42727ff1"
        cidr: "10.20.1.0/24" # (optional, must match CIDR used by the given subnet)

      eu-west-1b:
        id: "subnet-0a3b318d244552c2b"
        cidr: "10.20.2.0/24"  # (optional, must match CIDR used by the given subnet)

      eu-west-1c:
        id: "subnet-0e2ac1592a954b79b"
        cidr: "10.20.3.0/24"   # (optional, must match CIDR used by the given subnet)

    public:
      eu-west-1a:
        id: "subnet-071aff54ebbf36f28"
        cidr: "10.20.101.0/24" # (optional, must match CIDR used by the given subnet)

      eu-west-1b:
        id: "subnet-022b9fcb8991f03e6"
        cidr: "10.20.102.0/24"  # (optional, must match CIDR used by the given subnet)

      eu-west-1c:
        id: "subnet-06ed6fccd78c2b890"
        cidr: "10.20.103.0/24"   # (optional, must match CIDR used by the given subnet)           

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true    

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

git:
  repo:
    url: "git@github.com:polarpoint-io/fluxcd-shared-services"
    branch: master
    fluxPath: "flux/"
    user: "bainss"
    email: "bainss@users.noreply.github.com"
  operator:
    namespace: "flux"
    withHelm: true
