---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  releaseName: harbor
  targetNamespace: harbor
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: v1.1.1
  values:
    expose:
      tls:
        enabled: true
        secretName: ingress-cert-shared
      type: clusterIP
    externalURL: https://image.polarpoint.eu
    harborAdminPassword: admin
    persistence:
      enabled: true