---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: external-secrets
  targetNamespace: default
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets/
    name: external-secrets
    version: 5.2.0
  values:
    env:
      AWS_REGION: eu-west-1
      AWS_DEFAULT_REGION: eu-west-1