---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argocd-clientsecret
  namespace: continuous-delivery
spec:
  backendType: secretsManager
  data:
    - key: /service/argocd/clientsecret
      name: password