---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-ssh-access
  namespace: continuous-integration 
spec:
  backendType: secretsManager
  dataFrom:
    - service/github/privateSSHKey    