---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-escapehatchsecret
  namespace: continuous-integration
spec:
  backendType: secretsManager
  data:
    - key: /service/jenkins/escapehatchsecret
      name: password