---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-personal-access-token 
spec:
  backendType: secretsManager
  data:
    - key: service/github/token
      name: password