---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: artifact-user-access
  namespace: continuous-integration 
spec:
  backendType: secretsManager
  data:
    - key: service/artifact/password
      name: password
    - key: service/artifact/username
      name: username