---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: github-personal-access-token 
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::700677256593:role/eksctl-devops-tooling-eks-service-account-role 
  data:
    - key: service/github/token
      name: password
    - key: service/github/user
      name: username