apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "jenkins-ingress"
  namespace: "continuous-integration"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: build.services.polcloud.org
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 'subnet-099a6aca8c1945a64, subnet-098cdf9ee14d08734'
    alb.ingress.kubernetes.io/security-groups: sg-0fa4ba671a2d714fc
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:700677256593:certificate/d72c24ed-40f2-428e-9115-559b743e2c1c
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:eu-west-2:700677256593:userpool/eu-west-2_0xbR1RTuh", "UserPoolClientId":"vdhk4bd4ngr6ums1e7bcl9c9h", "UserPoolDomain":"dev-ops-tool-jenkins"}'
    alb.ingress.kubernetes.io/tags: Name=Jenkins-ALB,NAME=argocd-ALB-Test,owner=CloudOps,cost-centre=114773,environment=development,data-compliance=none
  labels:
    app: jenkins-ingress
spec:
  rules:
    - host: build.services.polcloud.org
      http:
        paths:
          - path: /*
            backend:
              serviceName: "jenkins"
              servicePort: 8080