apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-operator
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "3"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 2Gi
    - name: backup
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "2"
      image: virtuslab/jenkins-operator-backup-pvc:v0.0.6
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home
        name: jenkins-home
      - mountPath: /backup
        name: backup
    volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup
    basePlugins:
    - name: kubernetes
      version: "1.26.1"
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.40"
    - name: kubernetes-credentials-provider
      version: "0.15"      
    plugins:
    - name: ace-editor
      version: "1.1"
    - name: analysis-core
      version: "1.96"
    - name: analysis-model-api
      version: "8.1.3"
    - name: ansicolor
      version: "0.7.0"
    - name: antisamy-markup-formatter
      version: "2.0"
    - name: apache-httpcomponents-client-4-api
      version: "4.5.10-2.0"
    - name: authentication-tokens
      version: "1.3"
    - name: badge
      version: "1.8"
    - name: block-queued-job
      version: "0.2.0"
    - name: blueocean
      version: "1.23.2"
    - name: blueocean-autofavorite
      version: "1.2.4"
    - name: blueocean-bitbucket-pipeline
      version: "1.23.2"
    - name: blueocean-commons
      version: "1.23.2"
    - name: blueocean-config
      version: "1.23.2"
    - name: blueocean-core-js
      version: "1.23.2"
    - name: blueocean-dashboard
      version: "1.23.2"
    - name: blueocean-display-url
      version: "2.3.1"
    - name: blueocean-events
      version: "1.23.2"
    - name: blueocean-executor-info
      version: "1.23.2"
    - name: blueocean-git-pipeline
      version: "1.23.2"
    - name: blueocean-github-pipeline
      version: "1.23.2"
    - name: blueocean-i18n
      version: "1.23.2"
    - name: blueocean-jira
      version: "1.23.2"
    - name: blueocean-jwt
      version: "1.23.2"
    - name: blueocean-personalization
      version: "1.23.2"
    - name: blueocean-pipeline-api-impl
      version: "1.23.2"
    - name: blueocean-pipeline-editor
      version: "1.23.2"
    - name: blueocean-pipeline-scm-api
      version: "1.23.2"
    - name: blueocean-rest
      version: "1.23.2"
    - name: blueocean-rest-impl
      version: "1.23.2"
    - name: blueocean-web
      version: "1.23.2"
    - name: bootstrap4-api
      version: "4.5.0-1"
    - name: bouncycastle-api
      version: "2.18"
    - name: branch-api
      version: "2.5.6"
    - name: build-monitor-plugin
      version: "1.12+build.201809061734"
    - name: checkstyle
      version: "4.0.0"
    - name: cloudbees-bitbucket-branch-source
      version: "2.8.0"
    - name: cloudbees-folder
      version: "6.14"
    - name: code-coverage-api
      version: "1.1.6"
    - name: command-launcher
      version: "1.2"
    - name: credentials
      version: "2.3.9"
    - name: credentials-binding
      version: "1.23"
    - name: dashboard-view
      version: "2.12"
    - name: data-tables-api
      version: "1.10.21-2"
    - name: dependency-check-jenkins-plugin
      version: "5.1.1"
    - name: dependency-track
      version: "2.3.0"
    - name: display-url-api
      version: "2.3.2"
    - name: docker-commons
      version: "1.16"
    - name: docker-workflow
      version: "1.23"
    - name: durable-task
      version: "1.34"
    - name: echarts-api
      version: "4.7.0-4"
    - name: external-monitor-job
      version: "1.7"
    - name: favorite
      version: "2.3.2"
    - name: findbugs
      version: "5.0.0"
    - name: font-awesome-api
      version: "5.13.0-1"
    - name: forensics-api
      version: "0.7.0"
    - name: git-client
      version: "3.2.1"
    - name: git-server
      version: "1.9"
    - name: github
      version: "1.30.0"
    - name: github-api
      version: "1.114.2"
    - name: github-branch-source
      version: "2.8.2"
    - name: github-pullrequest
      version: "0.2.8"
    - name: greenballs
      version: "1.15"
    - name: handlebars
      version: "1.1.1"
    - name: handy-uri-templates-2-api
      version: "2.1.8-1.0"
    - name: htmlpublisher
      version: "1.23"
    - name: icon-shim
      version: "2.0.3"
    - name: ignore-committer-strategy
      version: "1.0.4"
    - name: jackson2-api
      version: "2.11.0"
    - name: jacoco
      version: "3.0.6"
    - name: javadoc
      version: "1.5"
    - name: jdk-tool
      version: "1.4"
    - name: jenkins-design-language
      version: "1.23.2"
    - name: jira
      version: "3.1.1"
    - name: job-dsl
      version: "1.77"
    - name: jquery-detached
      version: "1.2.1"
    - name: jquery3-api
      version: "3.5.1-1"
    - name: jsch
      version: "0.1.55.2"
    - name: junit
      version: "1.29"
    - name: kubernetes-client-api
      version: "4.9.2-2"
    - name: kubernetes-credentials
      version: "0.7.0"
    - name: ldap
      version: "1.24"
    - name: lockable-resources
      version: "2.8"
    - name: mailer
      version: "1.32"
    - name: matrix-auth
      version: "2.6.2"
    - name: matrix-project
      version: "1.17"
    - name: maven-plugin
      version: "3.6"
    - name: mercurial
      version: "2.10"
    - name: momentjs
      version: "1.1.1"
    - name: okhttp-api
      version: "3.12.12.2"
    - name: Office-365-Connector
      version: "4.13.2"
    - name: pam-auth
      version: "1.6"
    - name: performance
      version: "3.17"
    - name: pipeline-build-step
      version: "2.12"
    - name: pipeline-github-lib
      version: "1.0"
    - name: pipeline-graph-analysis
      version: "1.10"
    - name: pipeline-input-step
      version: "2.11"
    - name: pipeline-milestone-step
      version: "1.3.1"
    - name: pipeline-model-api
      version: "1.7.0"
    - name: pipeline-model-definition
      version: "1.7.0"
    - name: pipeline-model-extensions
      version: "1.7.0"
    - name: pipeline-rest-api
      version: "2.13"
    - name: pipeline-stage-step
      version: "2.3"
    - name: pipeline-stage-tags-metadata
      version: "1.7.0"
    - name: pipeline-stage-view
      version: "2.13"
    - name: plain-credentials
      version: "1.7"
    - name: plugin-util-api
      version: "1.2.2"
    - name: popper-api
      version: "1.16.0-6"
    - name: pubsub-light
      version: "1.13"
    - name: scm-api
      version: "2.6.3"
    - name: script-security
      version: "1.73"
    - name: simple-theme-plugin
      version: "0.6"
    - name: slack
      version: "2.40"
    - name: snakeyaml-api
      version: "1.26.4"
    - name: sonar
      version: "2.11"
    - name: sonar-quality-gates
      version: "1.3.1"
    - name: sse-gateway
      version: "1.23"
    - name: ssh-credentials
      version: "1.18.1"
    - name: structs
      version: "1.20"
    - name: theme-manager
      version: "0.1"
    - name: timestamper
      version: "1.11.3"
    - name: token-macro
      version: "2.12"
    - name: trilead-api
      version: "1.0.8"
    - name: variant
      version: "1.3"
    - name: warnings-ng
      version: "8.1.0"
    - name: windows-slaves
      version: "1.6"
    - name: workflow-api
      version: "2.40"
    - name: workflow-basic-steps
      version: "2.20"
    - name: workflow-cps
      version: "2.80"
    - name: workflow-cps-global-lib
      version: "2.16"
    - name: workflow-cps-global-lib-http
      version: "1.5.0"
    - name: workflow-durable-task-step
      version: "2.35"
    - name: workflow-multibranch
      version: "2.21"
    - name: workflow-scm-step
      version: "2.11"
    - name: workflow-step-api
      version: "2.22"
    - name: workflow-support
      version: "3.5"
    - name: zap-pipeline
      version: "1.9"
    - name: zapper
      version: "1.0.7"
  backup:
    containerName: backup
    action:
      exec:
        command:
          - /home/user/bin/backup.sh
    interval: 300 # seconds
    makeBackupBeforePodDeletion: true
  restore:
    containerName: backup
    action:
      exec:
        command:
          - /home/user/bin/restore.sh
  seedJobs:
  - id: jenkins-operator
    credentialType: basicSSHUserPrivateKey
    credentialID: github-ssh-access     
    targets: "*/**.groovy"
    description: "Jenkins Operator seeding repository"
    repositoryBranch: main
    repositoryUrl: https://github.com/pol-onesource/devops-groovy-jenkins-pipelines.git   
    githubPushTrigger: false
    buildPeriodically: "*/30 * * * *"
    additionalClasspath: "src lib/*jar" 
  configurationAsCode:
    configurations:
    - name: jenkins-operator-user-configuration-casc
  groovyScripts:
    configurations:
    - name: jenkins-operator-user-configuration-groovy