---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-alb-ingress
  namespace: kube-system
spec:
  releaseName: aws-alb-ingress
  chart:
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    name: aws-alb-ingress-controller
    version: 1.0.2
  values:
    clusterName: shared-services-eks
    ## Auto Discover awsRegion from ec2metadata, set this to true and omit awsRegion when ec2metadata is available.
    autoDiscoverAwsRegion: true
    ## Auto Discover awsVpcID from ec2metadata, set this to true and omit awsVpcID: " when ec2metadata is available.
    autoDiscoverAwsVpcID: true
    scope:
      ## If provided, the ALB ingress controller will only act on Ingress resources annotated with this class
      ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/controller/config.md#limiting-ingress-class
      ingressClass: alb
      ## If true, the ALB ingress controller will only act on Ingress resources in a single namespace
      ## Default: false; watch all namespaces
      singleNamespace: false
      ## If scope.singleNamespace=true, the ALB ingress controller will only act on Ingress resources in this namespace
      ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/controller/config.md#limiting-namespaces
      ## Default: namespace of the ALB ingress controller
      watchNamespace: ""